apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agent-sandbox-platform.fullname" . }}
  labels: {{- include "agent-sandbox-platform.labels" . | nindent 4 }}
rules:
  - apiGroups: ["extensions.agents.x-k8s.io"]
    resources: ["sandboxclaims"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: ["extensions.agents.x-k8s.io"]
    resources: ["sandboxwarmpools"]
    verbs: ["get"]
  - apiGroups: ["agents.x-k8s.io"]
    resources: ["sandboxes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent-sandbox-platform.fullname" . }}
  labels: {{- include "agent-sandbox-platform.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent-sandbox-platform.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "agent-sandbox-platform.fullname" . }}
